---
title: "workspace"
author: "Anne Fetrow"
date: "11/3/2020"
output: html_document
---
```{r "setup", warning=FALSE, message=FALSE}
# load libraries
library(tidyverse)
library(isoreader)
library(isocyclr)
library(microbialkitchen)
library(RDocumentation)
library(vctrs)
```

```{r}
O_isopath <- isopath() %>% 
              add_isotope("oxygen") %>% 
                add_component("gas", oxygen, variable = FALSE) %>% #Atmospheric CO2 in flux
                add_component("CA", oxygen) %>% #carbonic acid node
                add_component("bicarb", oxygen) %>% #bicarbonate anion node
                add_component("carb", oxygen) %>% #carboante anion node
                add_component("calcite", oxygen) %>% #calcite mineral node
                add_component("calcite_out", oxygen, variable = FALSE) %>% #out flux, mineral precipitation 
                  add_standard_reaction(gas == CA, eps.oxygen = e1, flux = atmo, name = "gas in") %>% 
                  add_standard_reaction(CA == bicarb, eps.oxygen = 0, flux = f2 * atmo) %>% 
                  add_standard_reaction(bicarb == carb, eps.oxygen = 0, flux = f3 *atmo) %>% 
                  add_standard_reaction(carb == calcite, eps.oxygen = e4, flux = f4 * atmo) %>%
                  add_standard_reaction(calcite == calcite_out, eps.oxygen = 0, flux = f4 * atmo, name = "min out")
```

#### Schematic
```{r rxn_diagram, fig.width = 8, fig.height = 5}
O_isopath %>% generate_reaction_diagram() + coord_equal()
```

```{r}
O_isopath <- O_isopath %>% 
                  set_parameters(
                    tibble(
                    # define three scenarios to model
                      scenario = c("pre-indust", "113 Ma", "55 Ma"),  #modeling pre-industrial pCO2, Creteceous'greenhouse' climate pCO2, and PETM
                    # define flux values and fractions
                      atmo = qty(c(280, 1500, 800), "mbar"), 
                      f2 = 0.1,
                      f3 = 0.1,
                      f4 = 0.1, 
                    # calc DIC species
                      calculate_DIC(
                        pH = 8, #adjust pH to system
                        pCO2 = qty(c(280, 1500, 800), "mbar") #two pCO2 scenarios
                        ),
                    # isotopic effects - temperature dependent
                      T.C = 25,
                      T.K = T.C + 273.15,
                      e1 = (1 / ((-373 / T.K) + 0.19)), # Mook (1986), CO2(g) to CO2(aq)
                      e2 = (-9866 / T.K + 24.12), # Mook (1986), CO2(aq) to HCO3
                      e3 = (1 / ((-867 / T.K) + 2.52)), #Mook (1986), HCO3 to CO3     #(1/0.99318 - 1)*1000, alpha(carb/bicarb)= 0.99318, Beck et al. 2015 
                      e4 = (1 / 1.00542 - 1) * 1000, # alpha(calcite/carb)= 1.00542, Beck et al. 2015
                    # define starting isotopic compositions
                      atmo.oxygen = 0, #atmoCO2 (pre-industrial) = 0permil. 
                      CA.oxygen = 0 , 
                      bicarb.oxygen = 0, 
                      carb.oxygen = 0, 
                      calcite.oxygen = 0 , 
                    # define pool sizes for variable component - pH = ? open system
                      atmo.pool = 1^-2,
                      CA.pool =  1/10^5,
                      bicarb.pool = 10^-0.5,
                      carb.pool = 1^-2.5
                    )
                  )

```

## Run model

Running the system of differential equations is easily done and uses the ode solvers of the **deSolve** package.

```{r, warning=FALSE}
model <- O_isopath %>% run_model(time_steps = 1000)
```